<?php
    echo "<!DOCTYPE html>\n";
    echo "<html>\n";
    echo "<head>\n";
    echo "    <title>CGI Example</title>\n";
    echo "    <link rel=\"stylesheet\" href=\"/WebServ/pages/styles.css\">\n";
    echo "</head>\n";
    echo "<body>\n";
    echo "<div class=\"header\">\n";
    echo "    <ul class=\"headerLinks\">\n";
    echo "        <li class=\"headerItem\" ><a href=\"/\">Root</a></li>\n";
    echo "        <li class=\"headerItem\" ><a href=\"/WebServ/pages/html/upload.html\">Upload</a></li>\n";
    echo "        <li class=\"headerItem\" ><a href=\"#\">Get</a></li>\n";
    echo "        <li class=\"headerItem\" ><a href=\"/WebServ/pages/html/post.html\">Post</a></li>\n";
    echo "        <li class=\"headerItem\" ><a href=\"/WebServ/cgiTests/php/login.php\">Login</a></li>\n";
    echo "    </ul>\n";
    echo "</div>\n";
    echo "<div class=\"container\">\n";
    echo "    <div class=\"head\">\n";
    echo "        <h1 class=\"bigTitle\">Hello, <font class=\"special\">CGI</font>!</h1>\n";
    echo "        <p>This is an example of a CGI script.</p>\n";
    echo "        <p>Bellow are some more examples image/video.</p>\n";
    echo "    </div>\n";
    echo "    <div>\n";
    echo "        <ul class=\"links\">\n";
    echo "            <li class=\"linkItem\"><a href=\"/WebServ/cgiTests/php/exampleImage.php\">Image</a></li>\n";
    echo "            <li class=\"linkItem\"><a href=\"/WebServ/cgiTests/php/exampleVideo.php\">Video</a></li>\n";
    echo "        </ul>\n";
    echo "    </div>";
    echo "</div>";
    echo "</body>\n";
    echo "</html>\n";
?>
